### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by Bunnybailey** [discord/discord-example-app#50]
Hello! Thank you to whoever is kind enough to read this and help me out. I've been following the guide for making a discord bot and i'm stuck at the spot where it asks me to add a Interactive Endpoint URL and i click the share button within glitch and then add the /interactions and try to save, but it says 

> Validation errors:
> interactions_endpoint_url: The specified interactions endpoint url could not be verified.
>

**Comment by JustinBeckwith** [comment]
Greetings! Typically when folks get this error, it's because they haven't updated their `.env` to include the right information.  Have a look here, and make sure you're following the steps in the getting started guide! 
https://github.com/discord/discord-example-app?tab=readme-ov-file#get-app-credentials

It could also be a result of the tunnel you're setting up not working.  After you start ngrok are you able to reach the site by directly navigating to https://<your_tunnel_url>/interactions?  

Beyond that - it's very helpful if you can provide us with information from the app itself.
